In [27]:
import pandas as pd

In [5]:
df=pd.DataFrame({'col1': [1,2,3,4,5],
               'col2': [45,56,57,48,35],
            'col3': "vanya agarwal loves chocolava cake".split()})

In [6]:
df

col1  col2       col3
0     1    45      vanya
1     2    56    agarwal
2     3    57      loves
3     4    48  chocolava
4     5    35       cake

In [7]:
df['col4']=df['col1']**2

In [8]:
df

col1  col2       col3  col4
0     1    45      vanya     1
1     2    56    agarwal     4
2     3    57      loves     9
3     4    48  chocolava    16
4     5    35       cake    25

In [9]:
df['col5']=df['col3'].str[0]

In [10]:
df

col1  col2       col3  col4 col5
0     1    45      vanya     1    v
1     2    56    agarwal     4    a
2     3    57      loves     9    l
3     4    48  chocolava    16    c
4     5    35       cake    25    c

In [14]:
def test1(a):
    if a =='v':
        return 'v'
    else:
        return 'z'

In [15]:
df['col6'] =df['col5'].apply(test1)

In [16]:
df

col1  col2       col3  col4 col5 col6
0     1    45      vanya     1    v    v
1     2    56    agarwal     4    a    z
2     3    57      loves     9    l    z
3     4    48  chocolava    16    c    z
4     5    35       cake    25    c    z

In [17]:
df['col7']=df['col3'].apply(len)

In [18]:
df

col1  col2       col3  col4 col5 col6  col7
0     1    45      vanya     1    v    v     5
1     2    56    agarwal     4    a    z     7
2     3    57      loves     9    l    z     5
3     4    48  chocolava    16    c    z     9
4     5    35       cake    25    c    z     4

In [1]:
import numpy as np


In [2]:
l=['sudh',1,2,3]

In [3]:
type(l)

list

In [4]:
np.array(l)

array(['sudh', '1', '2', '3'], dtype='<U11')

In [5]:
type(np.array(l))

numpy.ndarray

In [8]:
a=np.array([1,2,3.0])

In [9]:
a1=np.array([[1,2], [3,4]])

In [10]:
a

array([1., 2., 3.])

In [11]:
a1

array([[1, 2],
       [3, 4]])

In [12]:
a2=np.array([1,2,3,4], ndmin=4)

In [13]:
a2

array([[[[1, 2, 3, 4]]]])

In [14]:
np.asarray([1,2,3,4])

array([1, 2, 3, 4])

In [15]:
np.mat([1,2,3,4])

matrix([[1, 2, 3, 4]])

In [16]:
  np.fromfunction(lambda i,j : i==j ,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [29]:
a=np.fromfunction(lambda i, j: i*j, (3,2), dtype=int)

In [19]:
np.fromfunction(lambda i,j,z,p : i*j*z*p, (4,3,2,2))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 1.]],

        [[0., 0.],
         [0., 2.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 2.]],

        [[0., 0.],
         [0., 4.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 3.]],

        [[0., 0.],
         [0., 6.]]]])

In [21]:
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [37]:
a.ndim


2

In [38]:
a.size

6

In [39]:
a.shape

(3, 2)

In [40]:
a.dtype

dtype('int32')

In [30]:
pd.DataFrame(a)    #it an only convert 2d array 

0  1
0  0  0
1  0  1
2  0  2

In [33]:
np.random.rand(10,2)

array([[0.56685245, 0.33946089],
       [0.22187897, 0.15064561],
       [0.29595368, 0.21868244],
       [0.35126654, 0.57575554],
       [0.31703288, 0.80761413],
       [0.9422251 , 0.79496496],
       [0.92805189, 0.47304563],
       [0.99820694, 0.70320952],
       [0.47337425, 0.82087307],
       [0.18226097, 0.65410111]])

In [35]:
np.random.randint(10,20)

19

In [36]:
np.random.randn(10,2)       # it will generate the numbers whose average is equal to 0 n standard devaition is also equal to 0

array([[ 0.97524505,  0.01651818],
       [-0.52705631,  1.12997301],
       [ 1.52387961, -1.53853184],
       [-1.21720939,  1.53456172],
       [-1.44950313,  0.58354991],
       [-1.18928752, -0.9705921 ],
       [ 0.29374846,  0.13832641],
       [-1.76366468, -0.04179012],
       [ 0.31210275,  0.35909436],
       [-0.96504547,  1.51758345]])

In [45]:
a1=np.fromfunction(lambda i, j,z: i*j*z, (4,3,2), dtype=int)

In [46]:
a1.shape

(4, 3, 2)

In [48]:
a1.size

24

In [49]:
a1.reshape(12,2)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 4],
       [0, 0],
       [0, 3],
       [0, 6]])

In [50]:
a1.reshape(12,-1)  #-1 will automatically be change to 2 it will always the multiple if the size

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 4],
       [0, 0],
       [0, 3],
       [0, 6]])

In [52]:
np.arange(4,10,.2)

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [54]:
a=np.array([[1,2],[3,4]])

In [56]:
b=np.array([[4,5],[6,7]])

In [57]:
a


array([[1, 2],
       [3, 4]])

In [58]:
b

array([[4, 5],
       [6, 7]])

In [59]:
a*b      #it basically multiples only the indexes

array([[ 4, 10],
       [18, 28]])

In [62]:
m=a@b   #this is basically multiples the elements

In [63]:
m/0


C:\Users\DELL\AppData\Local\Temp\ipykernel_24064\4271266742.py:1: RuntimeWarning: divide by zero encountered in divide
  m/0


array([[inf, inf],
       [inf, inf]])